export class HUD {
  constructor() {
    this.container=document.createElement('div');
    this.container.id='hud';
    this.container.innerHTML=`<div id="crosshair"><div class="ch ch-h"></div><div class="ch ch-v"></div><div class="ch-dot"></div></div><div id="health-bar"><div id="health-fill"></div><div id="health-text">100</div></div><div id="kill-feed"></div><div id="hit-marker" style="display:none;"><div class="hm hm-1"></div><div class="hm hm-2"></div><div class="hm hm-3"></div><div class="hm hm-4"></div></div><div id="damage-overlay" style="display:none;"></div>`;
    document.body.appendChild(this.container);
    const style=document.createElement('style');
    style.textContent=`#hud{position:fixed;inset:0;pointer-events:none;z-index:100;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif}#crosshair{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}.ch{position:absolute;background:rgba(255,255,255,.82)}.ch-h{width:20px;height:2px;top:-1px;left:-10px}.ch-v{width:2px;height:20px;top:-10px;left:-1px}.ch-dot{position:absolute;width:4px;height:4px;background:rgba(255,255,255,.95);border-radius:50%;top:-2px;left:-2px}#health-bar{position:absolute;top:max(18px,env(safe-area-inset-top));left:max(18px,env(safe-area-inset-left));width:150px;height:20px;background:rgba(0,0,0,.55);border:1px solid rgba(255,255,255,.3);border-radius:4px;overflow:hidden}#health-fill{width:100%;height:100%;background:linear-gradient(90deg,#22cc44,#44ee66);transition:width .2s ease}#health-text{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:white;font-size:12px;font-weight:bold;text-shadow:1px 1px 2px #000}#kill-feed{position:absolute;top:max(20px,env(safe-area-inset-top));right:max(20px,env(safe-area-inset-right));text-align:right}.kill-msg{color:white;font-size:15px;font-weight:bold;text-shadow:2px 2px 4px #000;padding:4px 8px;margin-bottom:4px;animation:fadeOut 3s forwards}@keyframes fadeOut{0%{opacity:1}70%{opacity:1}100%{opacity:0}}#hit-marker{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}.hm{position:absolute;width:12px;height:2px;background:white}.hm-1{transform:translate(-12px,-12px) rotate(45deg)}.hm-2{transform:translate(6px,-12px) rotate(-45deg)}.hm-3{transform:translate(-12px,6px) rotate(-45deg)}.hm-4{transform:translate(6px,6px) rotate(45deg)}#damage-overlay{position:fixed;inset:0;background:radial-gradient(ellipse at center,transparent 50%,rgba(255,0,0,.4) 100%);pointer-events:none}`;
    document.head.appendChild(style); this.styleEl=style;
    this.healthFill=document.getElementById('health-fill');this.healthText=document.getElementById('health-text');this.killFeed=document.getElementById('kill-feed');this.hitMarker=document.getElementById('hit-marker');this.damageOverlay=document.getElementById('damage-overlay');
  }
  setHealth(hp){const pct=Math.max(0,Math.min(100,hp));this.healthFill.style.width=pct+'%';this.healthText.textContent=pct;if(pct>60)this.healthFill.style.background='linear-gradient(90deg,#22cc44,#44ee66)';else if(pct>30)this.healthFill.style.background='linear-gradient(90deg,#ccaa22,#eecc44)';else this.healthFill.style.background='linear-gradient(90deg,#cc2222,#ee4444)';}
  showHitMarker(){this.hitMarker.style.display='block';setTimeout(()=>{this.hitMarker.style.display='none';},200);}
  showDamage(){this.damageOverlay.style.display='block';setTimeout(()=>{this.damageOverlay.style.display='none';},300);}
  addKillMessage(msg){const div=document.createElement('div');div.className='kill-msg';div.textContent=msg;this.killFeed.appendChild(div);setTimeout(()=>div.remove(),3000);}
  destroy(){this.container.remove();this.styleEl.remove();}
}
