import { Room } from 'colyseus';
import { StrikeState, PlayerState } from './state.js';
import { WEAPONS, BUY_ITEMS, weaponById } from '../shared/weapons.js';
import { SPAWNS, collides, insideSite } from '../shared/map.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const TICK=50, FREEZE=8000, ROUND=105000, POST=5000, BOMB=40000, PLANT=3000, DEFUSE=5000, SPEED=6.2;
const cleanName=v=>(String(v||'player').replace(/[^a-zA-Z0-9_\- áéíóúÁÉÍÓÚ]/g,'').trim().slice(0,16)||'player');
export default class StrikeRoom extends Room {
  maxClients=10;
  onCreate(){
    this.setState(new StrikeState()); this.inputs=new Map(); this.lastShot=new Map(); this.reloadEnd=new Map(); this.useStart=new Map(); this.useHeld=new Set();
    this.onMessage('input',(c,m)=>this.input(c,m)); this.onMessage('shoot',(c,m)=>this.shoot(c,m)); this.onMessage('reload',c=>this.reload(c)); this.onMessage('buy',(c,m)=>this.buy(c,m));
    this.onMessage('use',c=>{this.useHeld.add(c.sessionId);this.use(c)}); this.onMessage('useStop',c=>this.stopUse(c.sessionId));
    this.setSimulationInterval(dt=>this.tick(dt/1000),TICK);
  }
  onJoin(c,o={}){const p=new PlayerState();p.name=cleanName(o.name);p.team=this.pickTeam();this.state.players.set(c.sessionId,p);this.inputs.set(c.sessionId,{forward:0,right:0});this.spawn(c.sessionId,false);this.broadcast('event',{type:'join',text:`${p.name} joined ${p.team}`});this.maybeStart();}
  onLeave(c){const p=this.state.players.get(c.sessionId);if(p?.hasBomb)this.dropBomb(p);this.state.players.delete(c.sessionId);this.inputs.delete(c.sessionId);this.stopUse(c.sessionId);if(this.state.players.size<2){this.state.phase='waiting';this.state.phaseEndsAt=0;}}
  pickTeam(){let a=0,d=0;this.state.players.forEach(p=>p.team==='attackers'?a++:d++);return a<=d?'attackers':'defenders';}
  maybeStart(){if(this.state.phase==='waiting'&&this.state.players.size>=2)this.startRound();}
  spawn(sid,reset=true,index=0){const p=this.state.players.get(sid);if(!p)return;const s=SPAWNS[p.team][index%SPAWNS[p.team].length];p.x=s.x;p.z=s.z;p.y=0;p.yaw=p.team==='attackers'?Math.PI/2:-Math.PI/2;p.pitch=0;p.hp=100;p.alive=true;p.hasBomb=false;p.reloading=false;if(reset){p.weapon='sidearm';p.ammo=WEAPONS.sidearm.mag;p.reserveAmmo=WEAPONS.sidearm.reserve;}}
  startRound(){this.state.round++;this.state.phase='freeze';this.state.phaseEndsAt=Date.now()+FREEZE;this.state.reason='Buy phase';this.state.roundWinner='';this.resetBomb();let ai=0,di=0;this.state.players.forEach((p,sid)=>this.spawn(sid,true,p.team==='attackers'?ai++:di++));const carrier=[...this.state.players.entries()].find(([,p])=>p.team==='attackers');if(carrier){carrier[1].hasBomb=true;this.state.bombState='carried';this.state.bombCarrier=carrier[0];}this.broadcast('event',{type:'round',text:`Round ${this.state.round} — buy phase`});}
  resetBomb(){this.state.bombState='idle';this.state.bombCarrier='';this.state.bombX=0;this.state.bombZ=0;this.state.bombSite='';this.state.bombExplodesAt=0;this.state.planter='';this.state.plantProgress=0;this.state.defuser='';this.state.defuseProgress=0;this.useStart.clear();this.useHeld.clear();}
  input(c,m={}){const p=this.state.players.get(c.sessionId);if(!p)return;this.inputs.set(c.sessionId,{forward:clamp(+m.forward||0,-1,1),right:clamp(+m.right||0,-1,1)});if(Number.isFinite(+m.yaw))p.yaw=+m.yaw;if(Number.isFinite(+m.pitch))p.pitch=clamp(+m.pitch,-1.35,1.35);}
  tick(dt){const now=Date.now();this.state.players.forEach((p,sid)=>{if(!p.alive)return;if(this.state.phase==='live')this.move(p,this.inputs.get(sid),dt);this.finishReload(p,sid,now)});this.useTick(now);this.pickupBomb();if(this.state.phase==='waiting'){this.maybeStart();return;}if(this.state.phase==='freeze'&&now>=this.state.phaseEndsAt){this.state.phase='live';this.state.phaseEndsAt=now+ROUND;this.broadcast('event',{type:'round',text:'GO!'});return;}if(this.state.phase==='live'){if(this.state.bombState==='planted'&&now>=this.state.bombExplodesAt){this.state.bombState='exploded';return this.endRound('attackers','Bomb exploded');}if(this.state.bombState!=='planted'&&now>=this.state.phaseEndsAt)return this.endRound('defenders','Time expired');this.elimination();return;}if(this.state.phase==='post'&&now>=this.state.phaseEndsAt){if(this.state.attackersScore>=9||this.state.defendersScore>=9||this.state.round>=17){this.state.attackersScore=0;this.state.defendersScore=0;this.state.round=0;}this.state.players.size>=2?this.startRound():this.state.phase='waiting';}}
  move(p,i={forward:0,right:0},dt){let dx=Math.sin(p.yaw)*(+i.forward||0)+Math.cos(p.yaw)*(+i.right||0),dz=Math.cos(p.yaw)*(+i.forward||0)-Math.sin(p.yaw)*(+i.right||0);const l=Math.hypot(dx,dz);if(l>1){dx/=l;dz/=l}const nx=p.x+dx*SPEED*dt,nz=p.z+dz*SPEED*dt;if(!collides(nx,p.z))p.x=nx;if(!collides(p.x,nz))p.z=nz;}
  shoot(c,m={}){const p=this.state.players.get(c.sessionId);if(!p?.alive||this.state.phase!=='live'||p.reloading)return;const w=weaponById(p.weapon),now=Date.now();if(now-(this.lastShot.get(c.sessionId)||0)<60000/w.rpm||p.ammo<=0)return;this.lastShot.set(c.sessionId,now);p.ammo--;const yaw=Number.isFinite(+m.yaw)?+m.yaw:p.yaw,pitch=Number.isFinite(+m.pitch)?clamp(+m.pitch,-1.35,1.35):p.pitch,cp=Math.cos(pitch),dir={x:Math.sin(yaw)*cp,y:Math.sin(pitch),z:Math.cos(yaw)*cp},o={x:p.x,y:1.55,z:p.z};let best=null;this.state.players.forEach((t,sid)=>{if(sid===c.sessionId||!t.alive||t.team===p.team)return;const vx=t.x-o.x,vz=t.z-o.z,vy=.95-o.y,along=vx*dir.x+vy*dir.y+vz*dir.z;if(along<0||along>w.range)return;const px=o.x+dir.x*along,py=o.y+dir.y*along,pz=o.z+dir.z*along;const head=Math.hypot(px-t.x,py-1.55,pz-t.z),body=Math.hypot(px-t.x,py-.9,pz-t.z);const hit=head<.28||body<.58;if(hit&&(!best||along<best.dist))best={t,sid,head:head<.28,dist:along};});if(!best)return;let dmg=w.damage*(best.head?w.headMult:1);if(best.t.armor>0){const ab=Math.min(best.t.armor,dmg*.35);best.t.armor-=ab;dmg-=ab*.5;}best.t.hp=Math.max(0,best.t.hp-dmg);if(best.t.hp<=0)this.kill(best.sid,c.sessionId,best.head);}
  kill(vsid,ksid,head){const v=this.state.players.get(vsid),k=this.state.players.get(ksid);if(!v?.alive)return;v.alive=false;v.hp=0;v.deaths++;if(v.hasBomb)this.dropBomb(v);this.stopUse(vsid);if(k){k.kills++;k.money=Math.min(16000,k.money+weaponById(k.weapon).killReward);}this.broadcast('event',{type:'kill',killer:k?.name||'world',victim:v.name,weapon:k?.weapon||'',headshot:!!head});}
  dropBomb(p){p.hasBomb=false;this.state.bombState='dropped';this.state.bombCarrier='';this.state.bombX=p.x;this.state.bombZ=p.z;}
  pickupBomb(){if(this.state.phase!=='live'||this.state.bombState!=='dropped')return;this.state.players.forEach((p,sid)=>{if(this.state.bombState!=='dropped'||!p.alive||p.team!=='attackers')return;if(Math.hypot(p.x-this.state.bombX,p.z-this.state.bombZ)<=1.25){p.hasBomb=true;this.state.bombState='carried';this.state.bombCarrier=sid;}});}
  use(c){const p=this.state.players.get(c.sessionId);if(!p?.alive||this.state.phase!=='live')return;const sid=c.sessionId,now=Date.now();if(p.team==='attackers'&&p.hasBomb){const site=insideSite(p.x,p.z);if(!site)return;if(!this.useStart.has(sid))this.useStart.set(sid,now);this.state.bombState='planting';this.state.planter=sid;this.state.bombSite=site;}else if(p.team==='defenders'&&this.state.bombState==='planted'&&Math.hypot(p.x-this.state.bombX,p.z-this.state.bombZ)<=1.7){if(!this.useStart.has(sid))this.useStart.set(sid,now);this.state.defuser=sid;}}
  stopUse(sid){this.useHeld.delete(sid);this.useStart.delete(sid);if(this.state.planter===sid&&this.state.bombState==='planting'){const p=this.state.players.get(sid);this.state.bombState=p?.hasBomb?'carried':'dropped';this.state.planter='';this.state.plantProgress=0;this.state.bombSite='';}if(this.state.defuser===sid){this.state.defuser='';this.state.defuseProgress=0;}}
  useTick(now){const ps=this.state.planter;if(ps&&this.state.bombState==='planting'){const p=this.state.players.get(ps),st=this.useStart.get(ps),ok=p?.alive&&p.hasBomb&&this.useHeld.has(ps)&&insideSite(p.x,p.z)===this.state.bombSite;if(!ok||!st)this.stopUse(ps);else{this.state.plantProgress=clamp((now-st)/PLANT,0,1);if(now-st>=PLANT){p.hasBomb=false;this.state.bombState='planted';this.state.bombCarrier='';this.state.bombX=p.x;this.state.bombZ=p.z;this.state.bombExplodesAt=now+BOMB;this.state.planter='';this.state.plantProgress=0;this.useStart.delete(ps);this.broadcast('event',{type:'bomb',text:`Bomb planted at ${this.state.bombSite}`});}}}const ds=this.state.defuser;if(ds&&this.state.bombState==='planted'){const p=this.state.players.get(ds),st=this.useStart.get(ds),ok=p?.alive&&this.useHeld.has(ds)&&Math.hypot(p.x-this.state.bombX,p.z-this.state.bombZ)<=1.7;if(!ok||!st)this.stopUse(ds);else{this.state.defuseProgress=clamp((now-st)/DEFUSE,0,1);if(now-st>=DEFUSE){this.state.bombState='defused';this.endRound('defenders','Bomb defused');}}}}
  reload(c){const p=this.state.players.get(c.sessionId);if(!p?.alive||p.reloading)return;const w=weaponById(p.weapon);if(p.ammo>=w.mag||p.reserveAmmo<=0)return;p.reloading=true;this.reloadEnd.set(c.sessionId,Date.now()+w.reloadMs);}
  finishReload(p,sid,now){if(!p.reloading||now<(this.reloadEnd.get(sid)||Infinity))return;const w=weaponById(p.weapon),n=Math.min(w.mag-p.ammo,p.reserveAmmo);p.ammo+=n;p.reserveAmmo-=n;p.reloading=false;this.reloadEnd.delete(sid);}
  buy(c,m={}){const p=this.state.players.get(c.sessionId),it=BUY_ITEMS[String(m.id||'')];if(!p?.alive||this.state.phase!=='freeze'||!it||p.money<it.price)return;if(it.id==='armor'){if(p.armor>=100)return;p.money-=it.price;p.armor=100;return;}p.money-=it.price;p.weapon=it.id;p.ammo=it.mag;p.reserveAmmo=it.reserve;p.reloading=false;}
  elimination(){let a=0,d=0;this.state.players.forEach(p=>{if(p.alive)(p.team==='attackers'?a++:d++)});if(d===0)this.endRound('attackers','Defenders eliminated');else if(a===0&&this.state.bombState!=='planted')this.endRound('defenders','Attackers eliminated');}
  endRound(w,r){if(this.state.phase!=='live')return;this.state.phase='post';this.state.phaseEndsAt=Date.now()+POST;this.state.roundWinner=w;this.state.reason=r;if(w==='attackers')this.state.attackersScore++;else this.state.defendersScore++;this.state.players.forEach(p=>p.money=Math.min(16000,p.money+(p.team===w?3250:1900)));this.broadcast('event',{type:'roundEnd',winner:w,text:`${w.toUpperCase()} WIN — ${r}`});}
}
